### ISSUE TITLE
Long string in middleware code destroys the UI

### ISSUE THREAD

**Issue by picsoung** [APItools/monitor#37]
Today I encounter an UI bug.

If you paste a long string like a very long API key, and it's not wrapped then the UI is destroyed and looks funny.

![apitools_traffic_monitor](https://cloud.githubusercontent.com/assets/172072/6395410/3ece472a-bdd8-11e4-8855-9f06a7dae04b.png)

**Comment by vramosp** [comment]
@ddcesare fixed this one already, pending to be deployed.
