### ISSUE TITLE
Read middlewares from apitools/middleware

### ISSUE THREAD

**Issue by kikito** [APItools/monitor#46]
The middleware specs are hard-coded in the monitor. We should put some kind of mechanism in place to read from the apitools/middleware github repo instead / in addition to that.

**Comment by mikz** [comment]
AFAIK the middleware list is read from brain. See https://github.com/APItools/monitor/blob/master/lua/brain.lua#L33-L41
https://github.com/APItools/monitor/blob/master/app/assets/javascripts/controllers/middleware.coffee#L435-L436
etc

**Comment by kikito** [comment]
Well it seems there is a problem in Brain then. It always returns the generic middleware list.

This should return a list of middlewares specific to Ifeelgoods:

https://www.apitools.com/api/middleware/search?endpoint=https://api.ifeelgoods.com

But it returns the same thing as something for a not found API:

https://www.apitools.com/api/middleware/search?endpoint=foo


I have traced the issue to this line: 

https://github.com/3scale/brain/blob/master/app/models/api.rb#L25

That `try` masks an exception (`API#middleware` does not exist, the correct one is `API#related_middleware`), returns `nil`, and the line always returns the generic middleware list.

I am going to change it.
